create database practice;
use practice

  CREATE TABLE WORKER
(
    WORKER_ID INT NOT NULL,
    FIRST_NAME VARCHAR(30) UNIQUE,
    LAST_NAME VARCHAR(15),

    SALARY INT CHECK (SALARY > 100),
    DEPT_NAME VARCHAR(15),
    JOINING_DATE DATETIME,

    CONSTRAINT PK_WORKER PRIMARY KEY (WORKER_ID)
);
INSERT INTO WORKER(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, DEPT_NAME, JOINING_DATE)
VALUES
(1, 'Shahed', 'Uddin', 8500, 'IT', '2020-01-10 09:05:00'),
(2, 'Karim', 'Hasan', 12500, 'HR', '2020-03-15 10:10:00'),
(3, 'Soniya', 'Hridhi', 9000, 'Admin', '2020-06-20 09:20:00'),
(4, 'Asad', 'Islam', 15000, 'Finance', '2021-02-05 08:45:00'),
(5, 'Fahim', 'Ahmed', 11000, 'Admin', '2021-05-18 09:35:00'),
(6, 'Nusrat', 'Jahan', 16000, 'HR', '2021-08-22 10:00:00'),
(7, 'Rafi', 'Mahmud', 10500, 'IT', '2022-01-12 09:15:00'),
(8, 'Sadia', 'Akter', 9500, 'Admin', '2022-04-25 10:25:00'),
(9, 'Imran', 'Khan', 14000, 'Finance', '2022-07-30 08:55:00'),
(10, 'Arafat', 'Roy', 11500, 'HR', '2023-01-08 09:40:00');


select FIRST_NAME +' ' +LAST_NAME AS FULL_NAME FROM WORKER WHERE DEPT_NAME='IT';

select FIRST_NAME +' ' +LAST_NAME  AS FULL_NAME , SALARY  FROM WORKER WHERE  SALARY >10000;

SELECT UPPER(FIRST_NAME) AS NAME FROM WORKER;
SELECT LOWER(FIRST_NAME) AS NAME FROM WORKER;

SELECT FIRST_NAME, LEN(FIRST_NAME) AS LENGTH FROM WORKER;

SELECT *
FROM WORKER
WHERE FIRST_NAME LIKE 'A%';

SELECT LEFT(FIRST_NAME,3)
FROM WORKER;

SELECT RIGHT(LAST_NAME,2)
FROM WORKER;


SELECT FIRST_NAME, REPLACE(DEPT_NAME,'IT','TECH') AS DEPT
FROM WORKER;

SELECT TOP 5 FIRST_NAME + SPACE(10) + LAST_NAME AS FULL_NAME
FROM WORKER;

SELECT *FROM WORKER WHERE FIRST_NAME LIKE '%a%';

SELECT FIRST_NAME, REPLICATE(FIRST_NAME,2)
FROM WORKER;
SELECT FIRST_NAME, SUBSTRING(FIRST_NAME,2,3)
FROM WORKER;
SELECT *
FROM WORKER
WHERE SALARY BETWEEN 10000 AND 15000;

SELECT TOP 3 *
FROM WORKER
ORDER BY JOINING_DATE ASC;

SELECT DEPT_NAME, COUNT(*) AS TOTAL
FROM WORKER
GROUP BY DEPT_NAME;

SELECT *
FROM WORKER
WHERE SALARY = (SELECT MAX(SALARY) FROM WORKER);

SELECT DEPT_NAME, AVG(SALARY) AS AVG_SALARY
FROM WORKER
GROUP BY DEPT_NAME;

SELECT FIRST_NAME
FROM WORKER
WHERE FIRST_NAME = REVERSE(FIRST_NAME);

SELECT 
'Name: ' + UPPER(FIRST_NAME) + REPLICATE('_',5) + 'Salary: ' + CAST(SALARY AS VARCHAR)
AS OUTPUT FROM WORKER;

SELECT MAX(SALARY) AS SECOND_HIGHEST
FROM WORKER
WHERE SALARY < (SELECT MAX(SALARY) FROM WORKER);

SELECT DEPT_NAME, COUNT(*) AS TOTAL_WORKER
FROM WORKER
GROUP BY DEPT_NAME;